version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile.frontend # Use the frontend Dockerfile
    ports:
      - "60123:80"  # Map container port 80 to host port 80
    depends_on:
      - flask_app # Ensure the backend starts before the frontend

volumes:
  pgdata: {}